services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cacajogos
      POSTGRES_USER: cacajogos
      POSTGRES_PASSWORD: cacajogos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
